IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='asnaf_transformed_v3' AND xtype='U')
CREATE TABLE dbo.asnaf_transformed_v3 (
    idno INT IDENTITY(1,1) NOT NULL,
    SnapshotID UNIQUEIDENTIFIER NOT NULL,
    AsnafID UNIQUEIDENTIFIER PRIMARY KEY,
    AsnafName NVARCHAR(255),
    Createdby UNIQUEIDENTIFIER,
    DateCreated DATETIME,
    asnafStatus INT,
    Name NVARCHAR(255),
    IdentificationType INT,
    DateofBirth DATETIME,
    Age INT,
    MaritalStatus INT,
    Working NVARCHAR(255),
    Healthlevel INT,
    PhysicalCondition INT,
    Bank NVARCHAR(100),
    OtherName NVARCHAR(255),
    IdentificationNumIC NVARCHAR(12),
    BirthLocation NVARCHAR(255),
    Gender INT,
    IfMuallafDateInIslam DATETIME,
    Salary MONEY,
    Remarks NVARCHAR(MAX),
    ModeofPayment INT,
    BankAccountNum NVARCHAR(100),
    ResidentialStatus INT,
    PeriodStayInSelangorYear INT,
    Street1 NVARCHAR(255),
    Street2 NVARCHAR(255),
    Street3 NVARCHAR(255),
    City NVARCHAR(255),
    Postcode NVARCHAR(5),
    Branch NVARCHAR(100),
    BranchID NVARCHAR(255),
    State INT,
    Country INT,
    TelephoneNoHome NVARCHAR(100),
    TelephoneNoOffice NVARCHAR(100),
    MobilePhoneNum NVARCHAR(100),
    Emel NVARCHAR(100),
    Schooling INT,
    Education INT,
    HighestEducation INT,
    DateofApplication DATETIME,
    RegistrationPortalId INT,
    RegistrationStatus INT,
    RegistrationType INT,
    ExitAsnafRemark NVARCHAR(MAX),
    ExitAsnafReason NVARCHAR(MAX),
    DeceasedDate DATETIME,
    recipientType NVARCHAR(100),
    recipient NVARCHAR(100),
    District NVARCHAR(100),
    DistrictID NVARCHAR(255),
    Mosque NVARCHAR(255),
    MosqueID NVARCHAR(255),
    JenisPendaftaran NVARCHAR(50),
    Status NVARCHAR(50),
    Statecode INT,
    StatusAsnaf NVARCHAR(50),
    PostJson TEXT,
    ReturnJson TEXT,
    CRMAsnafID NVARCHAR(100),
    PINo NVARCHAR(100) DEFAULT (NULL),
    RegType NVARCHAR(100) DEFAULT (NULL),
    CRMReviewID NVARCHAR(100) DEFAULT (NULL),
    CRMRegistrationID NVARCHAR(100),
    Relationship NVARCHAR(100) DEFAULT (NULL),
    MasihTanggungan NVARCHAR(10) DEFAULT (NULL),
    recipientTypeAsnaf NVARCHAR(100),
    recipientTypeOrganization NVARCHAR(100),
    Ename NVARCHAR(100),
    Eposition NVARCHAR(100),
    Eoffice NVARCHAR(100),
    Erelation NVARCHAR(100),
    reviewRemarks NVARCHAR(MAX),
    resetBy NVARCHAR(100),
    healthCronic NVARCHAR(100),
    OKU_Physical NVARCHAR(100),
    OKU_Type NVARCHAR(100),
    OKU_Cause NVARCHAR(100),
    OKU_Cause_Level NVARCHAR(100),
    Uzur_Condition NVARCHAR(100),
    carecosts NVARCHAR(100),
    monthlytotal NVARCHAR(100),
    sector NVARCHAR(100),
    remarkwork NVARCHAR(MAX),
    vehicle NVARCHAR(100),
    vehicleothers NVARCHAR(100),
    namamajikan NVARCHAR(100),
    fishermenpoultryagricultural NVARCHAR(100),
    sewinghandicraftscookingnursery NVARCHAR(100),
    service NVARCHAR(100),
    othersskill NVARCHAR(100),
    othersskillremarks NVARCHAR(MAX),
    carpentry NVARCHAR(100),
    business NVARCHAR(100),
    portalID NVARCHAR(100) DEFAULT (NULL),
    regstatus NVARCHAR(50),
    kadarsewa MONEY,
    amilID NVARCHAR(50),
    AsnafCategory NVARCHAR(50),
    ModifiedBy UNIQUEIDENTIFIER,
    ModifiedOn DATETIME,
    hadkifayahRate INT,
    hadkifayah NVARCHAR(100),
    SAPCode NVARCHAR(50),
    SAPRemarks NVARCHAR(MAX),
    SAPIndicator INT,
    Blacklisted INT,
    TarikhMulaKFAMKBAM DATETIME
);
