IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='school_transformed_v7' AND xtype='U')
CREATE TABLE dbo.school_transformed_v7 (
    idno INT IDENTITY(1,1) NOT NULL,
    SchoolingID UNIQUEIDENTIFIER NOT NULL,
    SchoolingName NVARCHAR(255) NULL,
    SnapshotID UNIQUEIDENTIFIER NULL,
    AsnafID UNIQUEIDENTIFIER NULL,
    Schooling NVARCHAR(255) NULL,
    Schooling_TadikaID UNIQUEIDENTIFIER NULL,
    Schooling_Kebangsaan NVARCHAR(200) NULL,
    Schooling_KebangsaanID UNIQUEIDENTIFIER NULL,
    Schooling_Agama NVARCHAR(200) NULL,
    Schooling_AgamaID UNIQUEIDENTIFIER NULL,
    Schooling_MenengahID UNIQUEIDENTIFIER NULL,
    IPT_ID UNIQUEIDENTIFIER NULL,
    Schooling_Tahap NVARCHAR(50) NULL,
    Schooling_Datestart DATETIME NULL,
    Schooling_Dateend DATETIME NULL,
    Education INT NULL,
    hadkifayah NVARCHAR(100) NULL,
    hadkifayahRate INT NULL,
    masihTanggungan NVARCHAR(50) NULL,
    Statecode INT NULL,
    CreatedOn DATETIME NULL,
    CreatedBy UNIQUEIDENTIFIER NULL,
    ModifiedOn DATETIME NULL,
    ModifiedBy UNIQUEIDENTIFIER NULL,
    PRIMARY KEY (idno)
);
