IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='hadkifayah_transformed_v7' AND xtype='U')
CREATE TABLE dbo.hadkifayah_transformed_v7 (
    idno INT IDENTITY(1,1) NOT NULL,
    hadkifayahID UNIQUEIDENTIFIER NOT NULL,
    SnapshotID UNIQUEIDENTIFIER NULL,
    hadkifayahName NVARCHAR(200) NULL,
    Status NVARCHAR(50) NULL,
    Statecode INT NULL,
    BilAnakBelajarDiIPT INT NULL,
    AnakBelajarDiIPT MONEY NULL,
    JumlahAnakBelajarDiIPT MONEY NULL,
    BilAnakBersekolahberumur517tahun INT NULL,
    AnakBersekolahberumur517tahun MONEY NULL,
    JumlahAnakBersekolahberumur517tahun MONEY NULL,
    BilAnakTidakBersekolahberumur17tahunkebaw INT NULL,
    AnakTidakBersekolahberumur17tahunkebawah MONEY NULL,
    JumlahAnakTidakBersekolahberumur17tahunke MONEY NULL,
    BilDewasaberumur18tahunkeatasdantinggal INT NULL,
    Dewasaberumur18tahunkeatasdantinggalbers MONEY NULL,
    JumlahDewasaberumur18tahunkeatasdantingg MONEY NULL,
    BilPasangan INT NULL,
    Pasangan MONEY NULL,
    JumlahPasangan MONEY NULL,
    BilPasanganTidakBekerja INT NULL,
    PasanganTidakBekerja MONEY NULL,
    JumlahPasanganTidakBekerja MONEY NULL,
    FreeFullyPaidHouse MONEY NULL,
    HouseUnderInstallmentorRental MONEY NULL,
    House NVARCHAR(50) NULL,
    Rumah NVARCHAR(50) NULL,
    TotalHouseholdGrossIncome MONEY NULL,
    TotalHouseholdGrossIncomeTotalLiabilities MONEY NULL,
    TotalLiabilities MONEY NULL,
    CostOfChildCare MONEY NULL,
    DependentChildWithDisability MONEY NULL,
    MedicalCostsOfChronicIllness MONEY NULL,
    HouseholdGrossIncomeDTotalHadKifayahE MONEY NULL,
    householdgrossincomedtotalhadkifayahe_Base MONEY NULL,
    TotalHadKifayahE MONEY NULL,
    totalhadkifayahe_Base MONEY NULL,
    TotalHouseholdGrossIncomeD MONEY NULL,
    totalhouseholdgrossincomed_Base MONEY NULL,
    HouseholdID UNIQUEIDENTIFIER NULL,
    CategoryAsnaf NVARCHAR(50) NULL,
    CategoryHadKifayah NVARCHAR(50) NULL,
    AsnafID UNIQUEIDENTIFIER NULL,
    AsnafReviewID UNIQUEIDENTIFIER NULL,
    CreatedOn DATETIME NULL,
    CreatedBy UNIQUEIDENTIFIER NULL,
    ModifiedOn DATETIME NULL,
    ModifiedBy UNIQUEIDENTIFIER NULL,
    CONSTRAINT PK_Hadkifayah PRIMARY KEY CLUSTERED (hadkifayahID ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
