MERGE INTO dbo.Hadkifayah AS target
USING (VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?))
AS source (
    hadkifayahID, SnapshotID, hadkifayahName, Status, Statecode, BilAnakBelajarDiIPT, AnakBelajarDiIPT, JumlahAnakBelajarDiIPT, 
    BilAnakBersekolahberumur517tahun, AnakBersekolahberumur517tahun, JumlahAnakBersekolahberumur517tahun, 
    BilAnakTidakBersekolahberumur17tahunkebaw, AnakTidakBersekolahberumur17tahunkebawah, 
    JumlahAnakTidakBersekolahberumur17tahunke, BilDewasaberumur18tahunkeatasdantinggal, 
    Dewasaberumur18tahunkeatasdantinggalbers, JumlahDewasaberumur18tahunkeatasdantingg, 
    BilPasangan, Pasangan, JumlahPasangan, BilPasanganTidakBekerja, PasanganTidakBekerja, 
    JumlahPasanganTidakBekerja, FreeFullyPaidHouse, HouseUnderInstallmentorRental, House, Rumah, 
    TotalHouseholdGrossIncome, TotalHouseholdGrossIncomeTotalLiabilities, TotalLiabilities, CostOfChildCare, 
    DependentChildWithDisability, MedicalCostsOfChronicIllness, HouseholdGrossIncomeDTotalHadKifayahE, 
    householdgrossincomedtotalhadkifayahe_Base, TotalHadKifayahE, totalhadkifayahe_Base, TotalHouseholdGrossIncomeD, 
    totalhouseholdgrossincomed_Base, HouseholdID, CategoryAsnaf, CategoryHadKifayah, AsnafID, 
    AsnafReviewID, CreatedOn, CreatedBy, ModifiedOn, ModifiedBy
)
ON target.hadkifayahID = source.hadkifayahID
WHEN MATCHED THEN
    UPDATE SET
        target.SnapshotID = source.SnapshotID,
        target.hadkifayahName = source.hadkifayahName,
        target.Status = source.Status,
        target.Statecode = source.Statecode,
        target.BilAnakBelajarDiIPT = source.BilAnakBelajarDiIPT,
        target.AnakBelajarDiIPT = source.AnakBelajarDiIPT,
        target.JumlahAnakBelajarDiIPT = source.JumlahAnakBelajarDiIPT,
        target.BilAnakBersekolahberumur517tahun = source.BilAnakBersekolahberumur517tahun,
        target.AnakBersekolahberumur517tahun = source.AnakBersekolahberumur517tahun,
        target.JumlahAnakBersekolahberumur517tahun = source.JumlahAnakBersekolahberumur517tahun,
        target.BilAnakTidakBersekolahberumur17tahunkebaw = source.BilAnakTidakBersekolahberumur17tahunkebaw,
        target.AnakTidakBersekolahberumur17tahunkebawah = source.AnakTidakBersekolahberumur17tahunkebawah,
        target.JumlahAnakTidakBersekolahberumur17tahunke = source.JumlahAnakTidakBersekolahberumur17tahunke,
        target.BilDewasaberumur18tahunkeatasdantinggal = source.BilDewasaberumur18tahunkeatasdantinggal,
        target.Dewasaberumur18tahunkeatasdantinggalbers = source.Dewasaberumur18tahunkeatasdantinggalbers,
        target.JumlahDewasaberumur18tahunkeatasdantingg = source.JumlahDewasaberumur18tahunkeatasdantingg,
        target.BilPasangan = source.BilPasangan,
        target.Pasangan = source.Pasangan,
        target.JumlahPasangan = source.JumlahPasangan,
        target.BilPasanganTidakBekerja = source.BilPasanganTidakBekerja,
        target.PasanganTidakBekerja = source.PasanganTidakBekerja,
        target.JumlahPasanganTidakBekerja = source.JumlahPasanganTidakBekerja,
        target.FreeFullyPaidHouse = source.FreeFullyPaidHouse,
        target.HouseUnderInstallmentorRental = source.HouseUnderInstallmentorRental,
        target.House = source.House,
        target.Rumah = source.Rumah,
        target.TotalHouseholdGrossIncome = source.TotalHouseholdGrossIncome,
        target.TotalHouseholdGrossIncomeTotalLiabilities = source.TotalHouseholdGrossIncomeTotalLiabilities,
        target.TotalLiabilities = source.TotalLiabilities,
        target.CostOfChildCare = source.CostOfChildCare,
        target.DependentChildWithDisability = source.DependentChildWithDisability,
        target.MedicalCostsOfChronicIllness = source.MedicalCostsOfChronicIllness,
        target.HouseholdGrossIncomeDTotalHadKifayahE = source.HouseholdGrossIncomeDTotalHadKifayahE,
        target.householdgrossincomedtotalhadkifayahe_Base = source.householdgrossincomedtotalhadkifayahe_Base,
        target.TotalHadKifayahE = source.TotalHadKifayahE,
        target.totalhadkifayahe_Base = source.totalhadkifayahe_Base,
        target.TotalHouseholdGrossIncomeD = source.TotalHouseholdGrossIncomeD,
        target.totalhouseholdgrossincomed_Base = source.totalhouseholdgrossincomed_Base,
        target.HouseholdID = source.HouseholdID,
        target.CategoryAsnaf = source.CategoryAsnaf,
        target.CategoryHadKifayah = source.CategoryHadKifayah,
        target.AsnafID = source.AsnafID,
        target.AsnafReviewID = source.AsnafReviewID,
        target.CreatedOn = source.CreatedOn,
        target.CreatedBy = source.CreatedBy,
        target.ModifiedOn = source.ModifiedOn,
        target.ModifiedBy = source.ModifiedBy
WHEN NOT MATCHED THEN
    INSERT (
        hadkifayahID, SnapshotID, hadkifayahName, Status, Statecode, BilAnakBelajarDiIPT, AnakBelajarDiIPT, JumlahAnakBelajarDiIPT, 
        BilAnakBersekolahberumur517tahun, AnakBersekolahberumur517tahun, JumlahAnakBersekolahberumur517tahun, 
        BilAnakTidakBersekolahberumur17tahunkebaw, AnakTidakBersekolahberumur17tahunkebawah, 
        JumlahAnakTidakBersekolahberumur17tahunke, BilDewasaberumur18tahunkeatasdantinggal, 
        Dewasaberumur18tahunkeatasdantinggalbers, JumlahDewasaberumur18tahunkeatasdantingg, 
        BilPasangan, Pasangan, JumlahPasangan, BilPasanganTidakBekerja, PasanganTidakBekerja, 
        JumlahPasanganTidakBekerja, FreeFullyPaidHouse, HouseUnderInstallmentorRental, House, Rumah, 
        TotalHouseholdGrossIncome, TotalHouseholdGrossIncomeTotalLiabilities, TotalLiabilities, CostOfChildCare, 
        DependentChildWithDisability, MedicalCostsOfChronicIllness, HouseholdGrossIncomeDTotalHadKifayahE, 
        householdgrossincomedtotalhadkifayahe_Base, TotalHadKifayahE, totalhadkifayahe_Base, TotalHouseholdGrossIncomeD, 
        totalhouseholdgrossincomed_Base, HouseholdID, CategoryAsnaf, CategoryHadKifayah, AsnafID, 
        AsnafReviewID, CreatedOn, CreatedBy, ModifiedOn, ModifiedBy
    )
    VALUES (
        source.hadkifayahID, source.SnapshotID, source.hadkifayahName, source.Status, source.Statecode, 
        source.BilAnakBelajarDiIPT, source.AnakBelajarDiIPT, source.JumlahAnakBelajarDiIPT, 
        source.BilAnakBersekolahberumur517tahun, source.AnakBersekolahberumur517tahun, source.JumlahAnakBersekolahberumur517tahun, 
        source.BilAnakTidakBersekolahberumur17tahunkebaw, source.AnakTidakBersekolahberumur17tahunkebawah, 
        source.JumlahAnakTidakBersekolahberumur17tahunke, source.BilDewasaberumur18tahunkeatasdantinggal, 
        source.Dewasaberumur18tahunkeatasdantinggalbers, source.JumlahDewasaberumur18tahunkeatasdantingg, 
        source.BilPasangan, source.Pasangan, source.JumlahPasangan, source.BilPasanganTidakBekerja, source.PasanganTidakBekerja, 
        source.JumlahPasanganTidakBekerja, source.FreeFullyPaidHouse, source.HouseUnderInstallmentorRental, 
        source.House, source.Rumah, source.TotalHouseholdGrossIncome, source.TotalHouseholdGrossIncomeTotalLiabilities, 
        source.TotalLiabilities, source.CostOfChildCare, source.DependentChildWithDisability, 
        source.MedicalCostsOfChronicIllness, source.HouseholdGrossIncomeDTotalHadKifayahE, 
        source.householdgrossincomedtotalhadkifayahe_Base, source.TotalHadKifayahE, source.totalhadkifayahe_Base, 
        source.TotalHouseholdGrossIncomeD, source.totalhouseholdgrossincomed_Base, source.HouseholdID, 
        source.CategoryAsnaf, source.CategoryHadKifayah, source.AsnafID, source.AsnafReviewID, 
        source.CreatedOn, source.CreatedBy, source.ModifiedOn, source.ModifiedBy
    );
