MERGE INTO dbo.asnaf_transformed_v7 AS target
USING (VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?))
AS source (
    SnapshotID, AsnafID, AsnafName, Createdby, DateCreated, asnafStatus, Name, IdentificationType, 
    DateofBirth, Age, MaritalStatus, Working, Bank, OtherName, 
    IdentificationNumIC, BirthLocation, Gender, IfMuallafDateInIslam, Salary, Remarks, ModeofPayment, 
    BankAccountNum, ResidentialStatus, PeriodStayInSelangorYear, Street1, Street2, Street3, City, 
    Postcode, Branch, BranchID, State, Country, TelephoneNoHome, TelephoneNoOffice, MobilePhoneNum, 
    Emel, Schooling, Education, HighestEducation, DateofApplication, RegistrationPortalId, RegistrationStatus, 
    RegistrationType, ExitAsnafRemark, ExitAsnafReason, ExitDate,
    DeceasedDate, recipientType, recipient, District, DistrictID, Mosque, MosqueID, JenisPendaftaran, 
    Status, Statecode, StatusAsnaf, PostJson, ReturnJson, CRMAsnafID, PINo, RegType, CRMReviewID, 
    CRMRegistrationID, Relationship, MasihTanggungan, recipientTypeAsnaf, recipientTypeOrganization, 
    Ename, Eposition, Eoffice, Erelation, reviewRemarks, resetBy, Healthlevel, PhysicalCondition, healthCronic, OKU_Physical, 
    OKU_Type, OKU_Cause, OKU_Cause_Level, Uzur_Condition, carecosts, monthlytotal, sector, remarkwork, 
    vehicle, vehicleothers, namamajikan, fishermenpoultryagricultural, sewinghandicraftscookingnursery, 
    service, othersskill, othersskillremarks, carpentry, business, portalID, regstatus, kadarsewa, amilID, 
    AsnafCategory, ModifiedBy, ModifiedOn, hadkifayahRate, hadkifayah, SAPCode, SAPRemarks, SAPIndicator, 
    Blacklisted, TarikhMulaKFAMKBAM
)
ON target.AsnafID = source.AsnafID
WHEN MATCHED THEN
    UPDATE SET
        target.SnapshotID = source.SnapshotID,
        target.AsnafName = source.AsnafName,
        target.Emel = source.Emel,
        target.Age = source.Age,
        target.Createdby = source.Createdby,
        target.DateCreated = source.DateCreated,
        target.asnafStatus = source.asnafStatus,
        target.Name = source.Name,
        target.IdentificationType = source.IdentificationType,
        target.DateofBirth = source.DateofBirth,
        target.MaritalStatus = source.MaritalStatus,
        target.Working = source.Working,
        target.Bank = source.Bank,
        target.OtherName = source.OtherName,
        target.IdentificationNumIC = source.IdentificationNumIC,
        target.BirthLocation = source.BirthLocation,
        target.Gender = source.Gender,
        target.IfMuallafDateInIslam = source.IfMuallafDateInIslam,
        target.Salary = source.Salary,
        target.Remarks = source.Remarks,
        target.ModeofPayment = source.ModeofPayment,
        target.BankAccountNum = source.BankAccountNum,
        target.ResidentialStatus = source.ResidentialStatus,
        target.PeriodStayInSelangorYear = source.PeriodStayInSelangorYear,
        target.Street1 = source.Street1,
        target.Street2 = source.Street2,
        target.Street3 = source.Street3,
        target.City = source.City,
        target.Postcode = source.Postcode,
        target.Branch = source.Branch,
        target.BranchID = source.BranchID,
        target.State = source.State,
        target.Country = source.Country,
        target.TelephoneNoHome = source.TelephoneNoHome,
        target.TelephoneNoOffice = source.TelephoneNoOffice,
        target.MobilePhoneNum = source.MobilePhoneNum,
        target.Schooling = source.Schooling,
        target.Education = source.Education,
        target.HighestEducation = source.HighestEducation,
        target.DateofApplication = source.DateofApplication,
        target.RegistrationPortalId = source.RegistrationPortalId,
        target.RegistrationStatus = source.RegistrationStatus,
        target.RegistrationType = source.RegistrationType,
        target.ExitAsnafRemark = source.ExitAsnafRemark,
        target.ExitAsnafReason = source.ExitAsnafReason,
        target.ExitDate = source.ExitDate,
        target.DeceasedDate = source.DeceasedDate,
        target.recipientType = source.recipientType,
        target.recipient = source.recipient,
        target.District = source.District,
        target.DistrictID = source.DistrictID,
        target.Mosque = source.Mosque,
        target.MosqueID = source.MosqueID,
        target.JenisPendaftaran = source.JenisPendaftaran,
        target.Status = source.Status,
        target.Statecode = source.Statecode,
        target.StatusAsnaf = source.StatusAsnaf,
        target.PostJson = source.PostJson,
        target.ReturnJson = source.ReturnJson,
        target.CRMAsnafID = source.CRMAsnafID,
        target.PINo = source.PINo,
        target.RegType = source.RegType,
        target.CRMReviewID = source.CRMReviewID,
        target.CRMRegistrationID = source.CRMRegistrationID,
        target.Relationship = source.Relationship,
        target.MasihTanggungan = source.MasihTanggungan,
        target.recipientTypeAsnaf = source.recipientTypeAsnaf,
        target.recipientTypeOrganization = source.recipientTypeOrganization,
        target.Ename = source.Ename,
        target.Eposition = source.Eposition,
        target.Eoffice = source.Eoffice,
        target.Erelation = source.Erelation,
        target.reviewRemarks = source.reviewRemarks,
        target.resetBy = source.resetBy,
        target.Healthlevel = source.Healthlevel,
        target.PhysicalCondition = source.PhysicalCondition,
        target.healthCronic = source.healthCronic,
        target.OKU_Physical = source.OKU_Physical,
        target.OKU_Type = source.OKU_Type,
        target.OKU_Cause = source.OKU_Cause,
        target.OKU_Cause_Level = source.OKU_Cause_Level,
        target.Uzur_Condition = source.Uzur_Condition,
        target.carecosts = source.carecosts,
        target.monthlytotal = source.monthlytotal,
        target.sector = source.sector,
        target.remarkwork = source.remarkwork,
        target.vehicle = source.vehicle,
        target.vehicleothers = source.vehicleothers,
        target.namamajikan = source.namamajikan,
        target.fishermenpoultryagricultural = source.fishermenpoultryagricultural,
        target.sewinghandicraftscookingnursery = source.sewinghandicraftscookingnursery,
        target.service = source.service,
        target.othersskill = source.othersskill,
        target.othersskillremarks = source.othersskillremarks,
        target.carpentry = source.carpentry,
        target.business = source.business,
        target.portalID = source.portalID,
        target.regstatus = source.regstatus,
        target.kadarsewa = source.kadarsewa,
        target.amilID = source.amilID,
        target.AsnafCategory = source.AsnafCategory,
        target.ModifiedBy = source.ModifiedBy,
        target.ModifiedOn = source.ModifiedOn,
        target.hadkifayahRate = source.hadkifayahRate,
        target.hadkifayah = source.hadkifayah,
        target.SAPCode = source.SAPCode,
        target.SAPRemarks = source.SAPRemarks,
        target.SAPIndicator = source.SAPIndicator,
        target.Blacklisted = source.Blacklisted,
        target.TarikhMulaKFAMKBAM = source.TarikhMulaKFAMKBAM
WHEN NOT MATCHED THEN
    INSERT (
        SnapshotID, AsnafID, AsnafName, Createdby, DateCreated, asnafStatus, Name, IdentificationType, 
        DateofBirth, Age, MaritalStatus, Working, Bank, OtherName, 
        IdentificationNumIC, BirthLocation, Gender, IfMuallafDateInIslam, Salary, Remarks, ModeofPayment, 
        BankAccountNum, ResidentialStatus, PeriodStayInSelangorYear, Street1, Street2, Street3, City, 
        Postcode, Branch, BranchID, State, Country, TelephoneNoHome, TelephoneNoOffice, MobilePhoneNum, 
        Emel, Schooling, Education, HighestEducation, DateofApplication, RegistrationPortalId, RegistrationStatus, 
        RegistrationType, ExitAsnafRemark, ExitAsnafReason, ExitDate,
        DeceasedDate, recipientType, recipient, District, DistrictID, Mosque, MosqueID, JenisPendaftaran, 
        Status, Statecode, StatusAsnaf, PostJson, ReturnJson, CRMAsnafID, PINo, RegType, CRMReviewID, 
        CRMRegistrationID, Relationship, MasihTanggungan, recipientTypeAsnaf, recipientTypeOrganization, 
        Ename, Eposition, Eoffice, Erelation, reviewRemarks, resetBy, Healthlevel, PhysicalCondition, healthCronic, OKU_Physical, 
        OKU_Type, OKU_Cause, OKU_Cause_Level, Uzur_Condition, carecosts, monthlytotal, sector, remarkwork, 
        vehicle, vehicleothers, namamajikan, fishermenpoultryagricultural, sewinghandicraftscookingnursery, 
        service, othersskill, othersskillremarks, carpentry, business, portalID, regstatus, kadarsewa, amilID, 
        AsnafCategory, ModifiedBy, ModifiedOn, hadkifayahRate, hadkifayah, SAPCode, SAPRemarks, SAPIndicator, 
        Blacklisted, TarikhMulaKFAMKBAM
    )
    VALUES (
        source.SnapshotID, source.AsnafID, source.AsnafName, source.Createdby, source.DateCreated, source.asnafStatus, 
        source.Name, source.IdentificationType, source.DateofBirth, source.Age, source.MaritalStatus, source.Working, 
        source.Bank, source.OtherName, source.IdentificationNumIC, 
        source.BirthLocation, source.Gender, source.IfMuallafDateInIslam, source.Salary, source.Remarks, source.ModeofPayment, 
        source.BankAccountNum, source.ResidentialStatus, source.PeriodStayInSelangorYear, source.Street1, source.Street2, 
        source.Street3, source.City, source.Postcode, source.Branch, source.BranchID, source.State, source.Country, 
        source.TelephoneNoHome, source.TelephoneNoOffice, source.MobilePhoneNum, source.Emel, source.Schooling, 
        source.Education, source.HighestEducation, source.DateofApplication, source.RegistrationPortalId, source.RegistrationStatus, 
        source.RegistrationType, source.ExitAsnafRemark, source.ExitAsnafReason, source.ExitDate,
        source.DeceasedDate, source.recipientType, source.recipient, source.District, source.DistrictID, source.Mosque, 
        source.MosqueID, source.JenisPendaftaran, source.Status, source.Statecode, source.StatusAsnaf, source.PostJson, 
        source.ReturnJson, source.CRMAsnafID, source.PINo, source.RegType, source.CRMReviewID, source.CRMRegistrationID, 
        source.Relationship, source.MasihTanggungan, source.recipientTypeAsnaf, source.recipientTypeOrganization, source.Ename, 
        source.Eposition, source.Eoffice, source.Erelation, source.reviewRemarks, source.resetBy, source.Healthlevel, source.PhysicalCondition, source.healthCronic, 
        source.OKU_Physical, source.OKU_Type, source.OKU_Cause, source.OKU_Cause_Level, source.Uzur_Condition, source.carecosts, 
        source.monthlytotal, source.sector, source.remarkwork, source.vehicle, source.vehicleothers, source.namamajikan, 
        source.fishermenpoultryagricultural, source.sewinghandicraftscookingnursery, source.service, source.othersskill, 
        source.othersskillremarks, source.carpentry, source.business, source.portalID, source.regstatus, source.kadarsewa, 
        source.amilID, source.AsnafCategory, source.ModifiedBy, source.ModifiedOn, source.hadkifayahRate, source.hadkifayah, 
        source.SAPCode, source.SAPRemarks, source.SAPIndicator, source.Blacklisted, source.TarikhMulaKFAMKBAM
    );
