-- SELECT
--      (_airbyte_data->>'vwlzs_hadkifayahId')::uuid AS hadkifayahID,
--      UPPER(gen_random_uuid()::text) AS SnapshotID,
--      (_airbyte_data->>'vwlzs_name')::text AS hadkifayahName,
--      NULL::text AS Status, 
--      (_airbyte_data->>'statecode')::text AS Statecode,
--      (_airbyte_data->>'vwlzs_BilAnakBelajarDiIPT')::int AS BilAnakBelajarDiIPT,
--      (_airbyte_data->>'vwlzs_AnakBelajarDiIPT')::money AS AnakBelajarDiIPT,
--      (_airbyte_data->>'vwlzs_JumlahAnakBelajarDiIPT')::money AS JumlahAnakBelajarDiIPT,
--      (_airbyte_data->>'vwlzs_BilAnakBersekolahberumur517tahun')::int AS BilAnakBersekolahberumur517tahun,
--      (_airbyte_data->>'vwlzs_AnakBersekolahberumur517tahun')::int AS AnakBersekolahberumur517tahun,
--      (_airbyte_data->>'vwlzs_JumlahAnakBersekolahberumur517tahun')::money AS JumlahAnakBersekolahberumur517tahun,
--      (_airbyte_data->>'vwlzs_BilAnakTidakBersekolahberumur17tahunkebaw')::int AS BilAnakTidakBersekolahberumur17tahunkebaw,
--      (_airbyte_data->>'vwlzs_AnakTidakBersekolahberumur17tahunkebawah')::money AS AnakTidakBersekolahberumur17tahunkebawah,
--      (_airbyte_data->>'vwlzs_JumlahAnakTidakBersekolahberumur17tahunke')::money AS JumlahAnakTidakBersekolahberumur17tahunke,
--      (_airbyte_data->>'vwlzs_BilDewasaberumur18tahunkeatasdantinggal')::int AS BilDewasaberumur18tahunkeatasdantinggal,
--      (_airbyte_data->>'vwlzs_Dewasaberumur18tahunkeatasdantinggalbers')::money AS Dewasaberumur18tahunkeatasdantinggalbers,
--      (_airbyte_data->>'vwlzs_JumlahDewasaberumur18tahunkeatasdantingg')::money AS JumlahDewasaberumur18tahunkeatasdantingg,
--      (_airbyte_data->>'vwlzs_BilPasangan')::int AS BilPasangan,
--      (_airbyte_data->>'vwlzs_Pasangan')::money AS Pasangan,
--      (_airbyte_data->>'vwlzs_JumlahPasangan')::money AS JumlahPasangan, 
--      (_airbyte_data->>'vwlzs_BilPasanganTidakBekerja')::int AS BilPasanganTidakBekerja,
--      (_airbyte_data->>'vwlzs_PasanganTidakBekerja')::money AS PasanganTidakBekerja,
--      (_airbyte_data->>'vwlzs_JumlahPasanganTidakBekerja')::money AS JumlahPasanganTidakBekerja,
--      (_airbyte_data->>'vwlzs_FreeFullyPaidHouse')::money AS FreeFullyPaidHouse,
--      (_airbyte_data->>'vwlzs_HouseUnderInstallmentorRental')::money AS HouseUnderInstallmentorRental,
--      (_airbyte_data->>'vwlzs_House')::text AS House,
--      (_airbyte_data->>'vwlzs_Rumah')::text AS Rumah,
--      (_airbyte_data->>'vwlzs_TotalHouseholdGrossIncome')::money AS TotalHouseholdGrossIncome,
--      (_airbyte_data->>'vwlzs_TotalHouseholdGrossIncomeTotalLiabilities')::money AS TotalHouseholdGrossIncomeTotalLiabilities,
--      (_airbyte_data->>'vwlzs_TotalLiabilities')::money AS TotalLiabilities,
--      (_airbyte_data->>'vwlzs_CostOfChildCare')::money AS CostOfChildCare,
--      (_airbyte_data->>'vwlzs_DependentChildWithDisability')::money AS DependentChildWithDisability,
--      (_airbyte_data->>'vwlzs_MedicalCostsOfChronicIllness')::money AS MedicalCostsOfChronicIllness,
--      (_airbyte_data->>'vwlzs_HouseholdGrossIncomeDTotalHadKifayahE')::money AS HouseholdGrossIncomeDTotalHadKifayahE,
--      (_airbyte_data->>'vwlzs_householdgrossincomedtotalhadkifayahe_Base')::money AS householdgrossincomedtotalhadkifayahe_Base,
--      (_airbyte_data->>'vwlzs_TotalHadKifayahE')::money AS TotalHadKifayahE,
--      (_airbyte_data->>'vwlzs_totalhadkifayahe_Base')::money AS totalhadkifayahe_Base,
--      (_airbyte_data->>'vwlzs_TotalHouseholdGrossIncomeD')::money AS TotalHouseholdGrossIncomeD,
--      (_airbyte_data->>'vwlzs_totalhouseholdgrossincomed_Base')::money AS totalhouseholdgrossincomed_Base,
--      (_airbyte_data->>'vwlzs_HouseholdId')::uuid AS HouseholdID,
--      (_airbyte_data->>'vwlzs_CategoryAsnaf')::text AS CategoryAsnaf,
--      (_airbyte_data->>'vwlzs_CategoryHadKifayah')::text AS CategoryHadKifayah,
--      (_airbyte_data->>'vwlzs_AsnafId')::uuid AS AsnafID,
--      (_airbyte_data->>'vwlzs_AsnafReviewId')::uuid AS AsnafReviewID,
--      TO_CHAR((_airbyte_data->>'CreatedOn')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS CreatedOn,
--      (_airbyte_data->>'CreatedBy')::uuid AS CreatedBy,
--      TO_CHAR((_airbyte_data->>'ModifiedOn')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS ModifiedOn,
--      (_airbyte_data->>'ModifiedBy')::uuid AS ModifiedBy
-- FROM airbyte_internal.dbo_raw__stream_vwlzs_hadkifayah
-- ORDER BY (_airbyte_data->>'CreatedOn')::timestamp DESC
-- LIMIT 100000;

SELECT
     NULL::uuid AS "SnapshotID",
     "vwlzs_hadkifayahId"::uuid AS "hadkifayahID",
     "vwlzs_name"::text AS "hadkifayahName",
     NULL::text AS "Status", 
     "statecode"::text AS "Statecode",
     "vwlzs_BilAnakBelajarDiIPT"::int AS "BilAnakBelajarDiIPT",
     "vwlzs_AnakBelajarDiIPT"::money AS "AnakBelajarDiIPT",
     "vwlzs_JumlahAnakBelajarDiIPT"::money AS "JumlahAnakBelajarDiIPT",
     "vwlzs_BilAnakBersekolahberumur517tahun"::int AS "BilAnakBersekolahberumur517tahun",
     "vwlzs_AnakBersekolahberumur517tahun"::int AS "AnakBersekolahberumur517tahun",
     "vwlzs_JumlahAnakBersekolahberumur517tahun"::money AS "JumlahAnakBersekolahberumur517tahun",
     "vwlzs_BilAnakTidakBersekolahberumur17tahunkebaw"::int AS "BilAnakTidakBersekolahberumur17tahunkebaw",
     "vwlzs_AnakTidakBersekolahberumur17tahunkebawah"::money AS "AnakTidakBersekolahberumur17tahunkebawah",
     "vwlzs_JumlahAnakTidakBersekolahberumur17tahunke"::money AS "JumlahAnakTidakBersekolahberumur17tahunke",
     "vwlzs_BilDewasaberumur18tahunkeatasdantinggal"::int AS "BilDewasaberumur18tahunkeatasdantinggal",
     "vwlzs_Dewasaberumur18tahunkeatasdantinggalbers"::money AS "Dewasaberumur18tahunkeatasdantinggalbers",
     "vwlzs_JumlahDewasaberumur18tahunkeatasdantingg"::money AS "JumlahDewasaberumur18tahunkeatasdantingg",
     "vwlzs_BilPasangan"::int AS "BilPasangan",
     "vwlzs_Pasangan"::money AS "Pasangan",
     "vwlzs_JumlahPasangan"::money AS "JumlahPasangan", 
     "vwlzs_BilPasanganTidakBekerja"::int AS "BilPasanganTidakBekerja",
     "vwlzs_PasanganTidakBekerja"::money AS "PasanganTidakBekerja",
     "vwlzs_JumlahPasanganTidakBekerja"::money AS "JumlahPasanganTidakBekerja",
     "vwlzs_FreeFullyPaidHouse"::money AS "FreeFullyPaidHouse",
     "vwlzs_HouseUnderInstallmentorRental"::money AS "HouseUnderInstallmentorRental",
     "vwlzs_House"::text AS "House",
     "vwlzs_Rumah"::text AS "Rumah",
     "vwlzs_TotalHouseholdGrossIncome"::money AS "TotalHouseholdGrossIncome",
     "vwlzs_TotalHouseholdGrossIncomeTotalLiabilities"::money AS "TotalHouseholdGrossIncomeTotalLiabilities",
     "vwlzs_TotalLiabilities"::money AS "TotalLiabilities",
     "vwlzs_CostOfChildCare"::money AS "CostOfChildCare",
     "vwlzs_DependentChildWithDisability"::money AS "DependentChildWithDisability",
     "vwlzs_MedicalCostsOfChronicIllness"::money AS "MedicalCostsOfChronicIllness",
     "vwlzs_HouseholdGrossIncomeDTotalHadKifayahE"::money AS "HouseholdGrossIncomeDTotalHadKifayahE",
     "vwlzs_householdgrossincomedtotalhadkifayahe_Base"::money AS "householdgrossincomedtotalhadkifayahe_Base",
     "vwlzs_TotalHadKifayahE"::money AS "TotalHadKifayahE",
     "vwlzs_totalhadkifayahe_Base"::money AS "totalhadkifayahe_Base",
     "vwlzs_TotalHouseholdGrossIncomeD"::money AS "TotalHouseholdGrossIncomeD",
     "vwlzs_totalhouseholdgrossincomed_Base"::money AS "totalhouseholdgrossincomed_Base",
     "vwlzs_HouseholdId"::uuid AS "HouseholdID",
     "vwlzs_CategoryAsnaf"::text AS "CategoryAsnaf",
     "vwlzs_CategoryHadKifayah"::text AS "CategoryHadKifayah",
     "vwlzs_AsnafId"::uuid AS "AsnafID",
     "vwlzs_AsnafReviewId"::uuid AS "AsnafReviewID",
     TO_CHAR("CreatedOn", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "CreatedOn",
     "CreatedBy"::uuid AS "CreatedBy",
     TO_CHAR("ModifiedOn", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "ModifiedOn",
     "ModifiedBy"::uuid AS "ModifiedBy"
FROM dbo.vwlzs_hadkifayah;
