SELECT
     "vwlzs_schoolId"::uuid AS "SchoolingID",
     NULL::text AS "SchoolingName",
     NULL::uuid AS "SnapshotID",
     NULL::uuid AS "AsnafID",
     "vwlzs_SchoolCode"::text AS "Schooling",
     NULL::uuid AS "Schooling_TadikaID",
     NULL::text AS "Schooling_Kebangsaan",
     NULL::uuid AS "Schooling_KebangsaanID",
     NULL::text AS "Schooling_Agama",
     NULL::uuid AS "Schooling_AgamaID",
     NULL::uuid AS "Schooling_MenengahID",
     NULL::uuid AS "IPT_ID",
     NULL::text AS "Schooling_Tahap",
     NULL::text AS "Schooling_Datestart",
     NULL::text AS "Schooling_Dateend",
     NULL::text AS "Education",
     NULL::text AS "hadkifayah",
     NULL::text AS "hadkifayahRate",
     NULL::text AS "masihTanggungan",
     "statecode"::text AS "Statecode",
     TO_CHAR("CreatedOn", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "CreatedOn",
     "CreatedBy"::uuid AS "CreatedBy",
     TO_CHAR("ModifiedOn", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "ModifiedOn",
     "ModifiedBy"::uuid AS "ModifiedBy"
FROM dbo.vwlzs_school;
