-- SELECT
--     UPPER(gen_random_uuid()::text) AS SnapshotID,
--     (_airbyte_data->>'vwlzs_asnafId')::uuid AS AsnafID,
--     NULL::text AS AsnafName,
--     (_airbyte_data->>'CreatedBy')::uuid AS Createdby,
--     TO_CHAR((_airbyte_data->>'CreatedOn')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS DateCreated,
--     (_airbyte_data->>'vwlzs_Status')::int AS asnafStatus,
--     (_airbyte_data->>'vwlzs_name')::text AS Name,
--     (_airbyte_data->>'vwlzs_IdentificationType')::int AS IdentificationType,
--     TO_CHAR((_airbyte_data->>'vwlzs_DateofBirth')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS DateofBirth,
--     (_airbyte_data->>'vwlzs_Age')::int AS Age,
--     (_airbyte_data->>'vwlzs_MaritalStatus')::int AS MaritalStatus,
--     NULL::text AS Working,
--     (_airbyte_data->>'vwlzs_BankName')::text AS Bank,
--     (_airbyte_data->>'vwlzs_OtherName')::text AS OtherName,
--     (_airbyte_data->>'vwlzs_nric')::text AS IdentificationNumIC,
--     (_airbyte_data->>'vwlzs_PlaceofBirth')::text AS BirthLocation,
--     CASE WHEN (_airbyte_data->>'vwlzs_Gender') IN ('true', 'false')
--          THEN CASE WHEN (_airbyte_data->>'vwlzs_Gender')::boolean IS TRUE THEN 1 ELSE 0 END
--          ELSE NULL END AS Gender,
--     TO_CHAR((_airbyte_data->>'vwlzs_DateEmbraceIslamMuallafOnly')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS IfMuallafDateInIslam,
--     (_airbyte_data->>'vwlzs_Salary')::money AS Salary,
--     (_airbyte_data->>'vwlzs_Notes')::text AS Remarks,
--     (_airbyte_data->>'vwlzs_ModeofPayment')::int AS ModeofPayment,
--     (_airbyte_data->>'vwlzs_BankAccountNo')::text AS BankAccountNum,
--     (_airbyte_data->>'vwlzs_Residentialstatus')::int AS ResidentialStatus,
--     (_airbyte_data->>'vwlzs_PeriodStayInSelangorYear')::int AS PeriodStayInSelangorYear,
--     (_airbyte_data->>'vwlzs_Street1')::text AS Street1,
--     (_airbyte_data->>'vwlzs_Street2')::text AS Street2,
--     (_airbyte_data->>'vwlzs_Street3')::text AS Street3,
--     (_airbyte_data->>'vwlzs_City')::text AS City,
--     (_airbyte_data->>'vwlzs_Postcode')::text AS Postcode,
--     (_airbyte_data->>'vwlzs_BranchName')::text AS Branch,
--     (_airbyte_data->>'vwlzs_Branch')::text AS BranchID,
--     (_airbyte_data->>'vwlzs_State')::int AS State,
--     (_airbyte_data->>'vwlzs_Country')::int AS Country,
--     (_airbyte_data->>'vwlzs_TelephoneNoHome')::text AS TelephoneNoHome,
--     (_airbyte_data->>'vwlzs_TelephoneNoOffice')::text AS TelephoneNoOffice,
--     (_airbyte_data->>'vwlzs_MobileNo')::text AS MobilePhoneNum,
--     (_airbyte_data->>'vwlzs_Email')::text AS Emel,
--     (_airbyte_data->>'vwlzs_Schooling')::int AS Schooling,
--     (_airbyte_data->>'vwlzs_Education')::int AS Education,
--     (_airbyte_data->>'vwlzs_HighestEducation')::int AS HighestEducation,
--     NULL::timestamp AS DateofApplication,
--     NULL::int AS RegistrationPortalId,
--     NULL::int AS RegistrationStatus,
--     NULL::int AS RegistrationType,
--     (_airbyte_data->>'vwlzs_ExitAsnafRemarks')::text AS ExitAsnafRemark,
--     (_airbyte_data->>'vwlzs_ExitAsnafReason')::text AS ExitAsnafReason,
--     TO_CHAR((_airbyte_data->>'vwlzs_ExitDate')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS ExitDate,
--     TO_CHAR((_airbyte_data->>'vwlzs_DeceasedDate')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS DeceasedDate,
--     NULL::text AS recipientType,
--     NULL::text AS recipient,
--     (_airbyte_data->>'vwlzs_District')::text AS District,
--     NULL::text AS DistrictID,
--     (_airbyte_data->>'vwlzs_MosqueName')::text AS Mosque,
--     (_airbyte_data->>'vwlzs_Mosque')::uuid AS MosqueID,
--     NULL::text AS JenisPendaftaran,
--     (_airbyte_data->>'vwlzs_Status')::text AS Status,
--     (_airbyte_data->>'statecode')::int AS Statecode,
--     NULL::text AS StatusAsnaf,
--     NULL::text AS PostJson,
--     NULL::text AS ReturnJson,
--     NULL::text AS CRMAsnafID,
--     (_airbyte_data->>'vwlzs_PakId')::text AS PINo,
--     (_airbyte_data->>'vwlzs_RegType')::text AS RegType,
--     NULL::text AS CRMReviewID,
--     NULL::text AS CRMRegistrationID,
--     (_airbyte_data->>'vwlzs_Relationship')::text AS Relationship,
--     NULL::text AS MasihTanggungan,
--     NULL::text AS recipientTypeAsnaf,
--     NULL::text AS recipientTypeOrganization,
--     NULL::text AS Ename,
--     NULL::text AS Eposition,
--     NULL::text AS Eoffice,
--     NULL::text AS Erelation,
--     (_airbyte_data->>'vwlzs_RemarkJobStatus')::text AS reviewRemarks,
--     NULL::text AS resetBy,
--     (_airbyte_data->>'vwlzs_Healthlevel')::int AS Healthlevel,
--     (_airbyte_data->>'vwlzs_PhysicalCondition')::int AS PhysicalCondition,
--     (_airbyte_data->>'vwlzs_RemarkHealthLevel')::text AS healthCronic,
--     (_airbyte_data->>'vwlzs_PhysicalCondition')::text AS OKU_Physical,
--     (_airbyte_data->>'vwlzs_TypeofDisability')::text AS OKU_Type,
--     (_airbyte_data->>'vwlzs_ReasonofDisability')::text AS OKU_Cause,
--     (_airbyte_data->>'vwlzs_TheLevelofDisability')::text AS OKU_Cause_Level,
--     (_airbyte_data->>'vwlzs_Condition')::text AS Uzur_Condition,
--     (_airbyte_data->>'vwlzs_CareCosts')::text AS carecosts,
--     (_airbyte_data->>'vwlzs_MonthlyTotal')::money AS monthlytotal,
--     (_airbyte_data->>'vwlzs_Sector')::text AS sector,
--     (_airbyte_data->>'vwlzs_WorkRemark')::text AS remarkwork,
--     (_airbyte_data->>'vwlzs_vehicle')::text AS vehicle,
--     NULL::text AS vehicleothers,
--     (_airbyte_data->>'vwlzs_EmployeeName')::text AS namamajikan,
--     (_airbyte_data->>'vwlzs_FishermenPoultryAgricultural')::text AS fishermenpoultryagricultural,
--     (_airbyte_data->>'vwlzs_SewingHandicraftsCookingNursery')::text AS sewinghandicraftscookingnursery,
--     (_airbyte_data->>'vwlzs_Service')::text AS service,
--     (_airbyte_data->>'vwlzs_OthersSkillsRemarks')::text AS othersskill,
--     (_airbyte_data->>'vwlzs_othersremarks')::text AS othersskillremarks,
--     (_airbyte_data->>'vwlzs_Carpentry')::text AS carpentry,
--     (_airbyte_data->>'vwlzs_Business')::text AS business,
--     (_airbyte_data->>'vwlzs_AsnafPortalId')::text AS portalID,
--     NULL::text AS regstatus,
--     (_airbyte_data->>'vwlzs_kadarsewa')::money AS kadarsewa,
--     NULL::text AS amilID,
--     (_airbyte_data->>'vwlzs_CategoryAsnaf')::text AS AsnafCategory,
--     (_airbyte_data->>'vwlzs_ModifiedBy')::uuid AS ModifiedBy,
--     TO_CHAR((_airbyte_data->>'vwlzs_ModifiedOn')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS ModifiedOn,
--     NULL::int AS hadkifayahRate,
--     NULL::text AS hadkifayah,
--     (_airbyte_data->>'vwlzs_SAPCode')::text AS SAPCode,
--     (_airbyte_data->>'vwlzs_sapremarks')::text AS SAPRemarks,
--     CASE WHEN (_airbyte_data->>'vwlzs_SAPIndicator') IN ('true', 'false')
--          THEN CASE WHEN (_airbyte_data->>'vwlzs_SAPIndicator')::boolean IS TRUE THEN 1 ELSE 0 END
--          ELSE NULL END AS SAPIndicator,
--     CASE WHEN (_airbyte_data->>'vwlzs_Blacklisted') IN ('true', 'false')
--          THEN CASE WHEN (_airbyte_data->>'vwlzs_Blacklisted')::boolean IS TRUE THEN 1 ELSE 0 END
--          ELSE NULL END AS Blacklisted,
--     NULL::timestamp AS TarikhMulaKFAMKBAM
-- FROM airbyte_internal.dbo_raw__stream_vwlzs_asnaf
-- ORDER BY (_airbyte_data->>'CreatedOn')::timestamp DESC
-- LIMIT 100000;

SELECT
    UPPER(gen_random_uuid()::text) AS "SnapshotID",
    "vwlzs_asnafId"::uuid AS "AsnafID",
    NULL::text AS "AsnafName",
    "CreatedBy"::uuid AS "Createdby",
    TO_CHAR("CreatedOn", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "DateCreated",
    "vwlzs_Status"::int AS "asnafStatus",
    "vwlzs_name"::text AS "Name",
    "vwlzs_IdentificationType"::int AS "IdentificationType",
    TO_CHAR("vwlzs_DateofBirth", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "DateofBirth",
    "vwlzs_Age"::int AS "Age",
    "vwlzs_MaritalStatus"::int AS "MaritalStatus",
    NULL::text AS "Working",
    "vwlzs_BankName"::text AS "Bank",
    "vwlzs_OtherName"::text AS "OtherName",
    "vwlzs_nric"::text AS "IdentificationNumIC",
    "vwlzs_PlaceofBirth"::text AS "BirthLocation",
    CASE WHEN "vwlzs_Gender" IN ('true', 'false')
         THEN CASE WHEN "vwlzs_Gender"::boolean IS TRUE THEN 1 ELSE 0 END
         ELSE NULL END AS "Gender",
    TO_CHAR("vwlzs_DateEmbraceIslamMuallafOnly", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "IfMuallafDateInIslam",
    NULL::money AS "Salary",
    "vwlzs_Notes"::text AS "Remarks",
    "vwlzs_ModeofPayment"::int AS "ModeofPayment",
    "vwlzs_BankAccountNo"::text AS "BankAccountNum",
    "vwlzs_Residentialstatus"::int AS "ResidentialStatus",
    "vwlzs_PeriodStayInSelangorYear"::int AS "PeriodStayInSelangorYear",
    "vwlzs_Street1"::text AS "Street1",
    "vwlzs_Street2"::text AS "Street2",
    "vwlzs_Street3"::text AS "Street3",
    "vwlzs_City"::text AS "City",
    "vwlzs_Postcode"::text AS "Postcode",
    "vwlzs_BranchName"::text AS "Branch",
    "vwlzs_Branch"::text AS "BranchID",
    "vwlzs_State"::int AS "State",
    "vwlzs_Country"::int AS "Country",
    "vwlzs_TelephoneNoHome"::text AS "TelephoneNoHome",
    "vwlzs_TelephoneNoOffice"::text AS "TelephoneNoOffice",
    "vwlzs_MobileNo"::text AS "MobilePhoneNum",
    "vwlzs_Email"::text AS "Emel",
    "vwlzs_Schooling"::int AS "Schooling",
    "vwlzs_Education"::int AS "Education",
    "vwlzs_HighestEducation"::int AS "HighestEducation",
    NULL::timestamp AS "DateofApplication",
    NULL::int AS "RegistrationPortalId",
    NULL::int AS "RegistrationStatus",
    NULL::int AS "RegistrationType",
    "vwlzs_ExitAsnafRemarks"::text AS "ExitAsnafRemark",
    "vwlzs_ExitAsnafReason"::text AS "ExitAsnafReason",
    TO_CHAR("vwlzs_ExitDate", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "ExitDate",
    TO_CHAR("vwlzs_DeceasedDate", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "DeceasedDate",
    NULL::text AS "recipientType",
    NULL::text AS "recipient",
    "vwlzs_District"::text AS "District",
    NULL::text AS "DistrictID",
    "vwlzs_MosqueName"::text AS "Mosque",
    "vwlzs_Mosque"::uuid AS "MosqueID",
    NULL::text AS "JenisPendaftaran",
    "vwlzs_Status"::text AS "Status",
    "statecode"::int AS "Statecode",
    NULL::text AS "StatusAsnaf",
    NULL::text AS "PostJson",
    NULL::text AS "ReturnJson",
    NULL::text AS "CRMAsnafID",
    "vwlzs_PakId"::text AS "PINo",
    NULL::text AS "RegType",
    NULL::text AS "CRMReviewID",
    NULL::text AS "CRMRegistrationID",
    "vwlzs_Relationship"::text AS "Relationship",
    NULL::text AS "MasihTanggungan",
    NULL::text AS "recipientTypeAsnaf",
    NULL::text AS "recipientTypeOrganization",
    NULL::text AS "Ename",
    NULL::text AS "Eposition",
    NULL::text AS "Eoffice",
    NULL::text AS "Erelation",
    "vwlzs_RemarkJobStatus"::text AS "reviewRemarks",
    NULL::text AS "resetBy",
    "vwlzs_Healthlevel"::int AS "Healthlevel",
    "vwlzs_PhysicalCondition"::int AS "PhysicalCondition",
    "vwlzs_RemarkHealthLevel"::text AS "healthCronic",
    "vwlzs_PhysicalCondition"::text AS "OKU_Physical",
    "vwlzs_TypeofDisability"::text AS "OKU_Type",
    "vwlzs_ReasonofDisability"::text AS "OKU_Cause",
    "vwlzs_TheLevelofDisability"::text AS "OKU_Cause_Level",
    "vwlzs_Condition"::text AS "Uzur_Condition",
    "vwlzs_CareCosts"::text AS "carecosts",
    "vwlzs_MonthlyTotal"::money AS "monthlytotal",
    "vwlzs_Sector"::text AS "sector",
    "vwlzs_WorkRemark"::text AS "remarkwork",
    "vwlzs_vehicle"::text AS "vehicle",
    NULL::text AS "vehicleothers",
    "vwlzs_EmployeeName"::text AS "namamajikan",
    "vwlzs_FishermenPoultryAgricultural"::text AS "fishermenpoultryagricultural",
    "vwlzs_SewingHandicraftsCookingNursery"::text AS "sewinghandicraftscookingnursery",
    "vwlzs_Service"::text AS "service",
    "vwlzs_OthersSkillsRemarks"::text AS "othersskill",
    "vwlzs_othersremarks"::text AS "othersskillremarks",
    "vwlzs_Carpentry"::text AS "carpentry",
    "vwlzs_Business"::text AS "business",
    "vwlzs_AsnafPortalId"::text AS "portalID",
    NULL::text AS "regstatus",
    NULL::money AS "kadarsewa",
    NULL::text AS "amilID",
    "vwlzs_CategoryAsnaf"::text AS "AsnafCategory",
    "ModifiedBy"::uuid AS "ModifiedBy",
    TO_CHAR("ModifiedOn", 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS "ModifiedOn",
    NULL::int AS "hadkifayahRate",
    NULL::text AS "hadkifayah",
    "vwlzs_SAPCode"::text AS "SAPCode",
    "vwlzs_sapremarks"::text AS "SAPRemarks",
    CASE WHEN "vwlzs_SAPIndicator" IN ('true', 'false')
         THEN CASE WHEN "vwlzs_SAPIndicator"::boolean IS TRUE THEN 1 ELSE 0 END
         ELSE NULL END AS "SAPIndicator",
    CASE WHEN "vwlzs_Blacklisted" IN ('true', 'false')
         THEN CASE WHEN "vwlzs_Blacklisted"::boolean IS TRUE THEN 1 ELSE 0 END
         ELSE NULL END AS "Blacklisted",
    NULL::timestamp AS "TarikhMulaKFAMKBAM"
FROM dbo.vwlzs_asnaf;
