SELECT
    NEWID() AS SnapshotID,
    (_airbyte_data->>'vwlzs_asnafId')::uuid AS AsnafID,
    (_airbyte_data->>'vwlzs_AsnafRegistrationIdName')::text AS AsnafName,
    (_airbyte_data->>'CreatedBy')::uuid AS Createdby,
    TO_CHAR((_airbyte_data->>'CreatedOn')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS DateCreated,
    NULL::int AS asnafStatus,
    (_airbyte_data->>'vwlzs_name')::text AS Name,
    (_airbyte_data->>'vwlzs_IdentificationType')::int AS IdentificationType,
    TO_CHAR((_airbyte_data->>'vwlzs_DateofBirth')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS DateofBirth,
    (_airbyte_data->>'vwlzs_Age')::int AS Age,
    (_airbyte_data->>'vwlzs_MaritalStatus')::int AS MaritalStatus,
    NULL::text AS Working,
    (_airbyte_data->>'pak_Healthlevel')::int AS Healthlevel,
    (_airbyte_data->>'pak_OKU_Physical')::int AS PhysicalCondition,
    (_airbyte_data->>'pak_OKU_Physical')::int AS Remarkhealthlevel,
    (_airbyte_data->>'vwlzs_BankName')::text AS Bank,
    (_airbyte_data->>'vwlzs_OtherName')::text AS OtherName,
    (_airbyte_data->>'vwlzs_nric')::text AS IdentificationNumIC,
    (_airbyte_data->>'vwlzs_PlaceofBirth')::text AS BirthLocation,
    CASE WHEN (_airbyte_data->>'vwlzs_Gender') IN ('true', 'false')
         THEN CASE WHEN (_airbyte_data->>'vwlzs_Gender')::boolean IS TRUE THEN 1 ELSE 0 END
         ELSE NULL END AS Gender,
    NULL::timestamp AS IfMuallafDateInIslam,
    (_airbyte_data->>'vwlzs_Salary')::money AS Salary,
    (_airbyte_data->>'vwlzs_Notes')::text AS Remarks,
    (_airbyte_data->>'vwlzs_ModeofPayment')::int AS ModeofPayment,
    (_airbyte_data->>'vwlzs_BankAccountNo')::text AS BankAccountNum,
    (_airbyte_data->>'vwlzs_Residentialstatus')::int AS ResidentialStatus,
    (_airbyte_data->>'vwlzs_PeriodStayInSelangorYear')::int AS PeriodStayInSelangorYear,
    (_airbyte_data->>'vwlzs_Street1')::text AS Street1,
    (_airbyte_data->>'vwlzs_Street2')::text AS Street2,
    (_airbyte_data->>'vwlzs_Street3')::text AS Street3,
    (_airbyte_data->>'vwlzs_City')::text AS City,
    (_airbyte_data->>'vwlzs_Postcode')::text AS Postcode,
    (_airbyte_data->>'vwlzs_BranchName')::text AS Branch,
    NULL::text AS BranchID,
    (_airbyte_data->>'vwlzs_State')::int AS State,
    (_airbyte_data->>'vwlzs_Country')::int AS Country,
    (_airbyte_data->>'vwlzs_TelephoneNoHome')::text AS TelephoneNoHome,
    (_airbyte_data->>'vwlzs_TelephoneNoOffice')::text AS TelephoneNoOffice,
    (_airbyte_data->>'vwlzs_MobileNo')::text AS MobilePhoneNum,
    (_airbyte_data->>'vwlzs_Email')::text AS Emel,
    (_airbyte_data->>'vwlzs_Schooling')::int AS Schooling,
    (_airbyte_data->>'vwlzs_Education')::int AS Education,
    (_airbyte_data->>'vwlzs_HighestEducation')::int AS HighestEducation,
    NULL::timestamp AS DateofApplication,
    NULL::int AS RegistrationPortalId,
    NULL::int AS RegistrationStatus,
    NULL::int AS RegistrationType,
    NULL::text AS ExitAsnafRemark,
    NULL::text AS ExitAsnafReason,
    NULL::timestamp AS ExitDate, -- Added missing column
    TO_CHAR((_airbyte_data->>'vwlzs_DeceasedDate')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS DeceasedDate,
    NULL::text AS recipientType,
    NULL::text AS recipient,
    (_airbyte_data->>'vwlzs_District')::text AS District,
    NULL::text AS DistrictID,
    (_airbyte_data->>'vwlzs_Mosque')::text AS Mosque,
    NULL::text AS MosqueID,
    NULL::text AS JenisPendaftaran,
    (_airbyte_data->>'vwlzs_Status')::text AS Status,
    NULL::int AS Statecode,
    NULL::text AS StatusAsnaf,
    NULL::text AS PostJson,
    NULL::text AS ReturnJson,
    NULL::text AS CRMAsnafID,
    (_airbyte_data->>'vwlzs_PakId')::text AS PINo,
    (_airbyte_data->>'vwlzs_RegType')::text AS RegType,
    NULL::text AS CRMReviewID,
    NULL::text AS CRMRegistrationID,
    NULL::text AS Relationship,
    NULL::text AS MasihTanggungan,
    NULL::text AS recipientTypeAsnaf,
    NULL::text AS recipientTypeOrganization,
    NULL::text AS Ename,
    NULL::text AS Eposition,
    NULL::text AS Eoffice,
    NULL::text AS Erelation,
    (_airbyte_data->>'vwlzs_RemarkJobStatus')::text AS reviewRemarks,
    NULL::text AS resetBy,
    NULL::text AS healthCronic,
    (_airbyte_data->>'pak_OKU_Physical')::text AS OKU_Physical,
    NULL::text AS OKU_Type,
    NULL::text AS OKU_Cause,
    NULL::text AS OKU_Cause_Level,
    NULL::text AS Uzur_Condition,
    (_airbyte_data->>'vwlzs_CareCosts')::text AS carecosts,
    NULL::money AS monthlytotal,
    (_airbyte_data->>'vwlzs_Sector')::text AS sector,
    (_airbyte_data->>'vwlzs_WorkRemark')::text AS remarkwork,
    (_airbyte_data->>'vwlzs_vehicle')::text AS vehicle,
    NULL::text AS vehicleothers,
    NULL::text AS namamajikan,
    NULL::text AS fishermenpoultryagricultural,
    NULL::text AS sewinghandicraftscookingnursery,
    (_airbyte_data->>'vwlzs_Service')::text AS service,
    NULL::text AS othersskill,
    (_airbyte_data->>'vwlzs_othersremarks')::text AS othersskillremarks,
    NULL::text AS carpentry,
    (_airbyte_data->>'vwlzs_Business')::text AS business,
    NULL::text AS portalID,
    NULL::text AS regstatus,
    (_airbyte_data->>'vwlzs_kadarsewa')::money AS kadarsewa,
    NULL::text AS amilID,
    NULL::text AS AsnafCategory,
    (_airbyte_data->>'vwlzs_ModifiedBy')::uuid AS ModifiedBy,
    TO_CHAR((_airbyte_data->>'vwlzs_ModifiedOn')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') AS ModifiedOn,
    NULL::int AS hadkifayahRate,
    NULL::text AS hadkifayah,
    (_airbyte_data->>'vwlzs_SAPCode')::text AS SAPCode,
    (_airbyte_data->>'vwlzs_sapremarks')::text AS SAPRemarks,
    CASE WHEN (_airbyte_data->>'vwlzs_SAPIndicator') IN ('true', 'false')
         THEN CASE WHEN (_airbyte_data->>'vwlzs_SAPIndicator')::boolean IS TRUE THEN 1 ELSE 0 END
         ELSE NULL END AS SAPIndicator,
    CASE WHEN (_airbyte_data->>'vwlzs_Blacklisted') IN ('true', 'false')
         THEN CASE WHEN (_airbyte_data->>'vwlzs_Blacklisted')::boolean IS TRUE THEN 1 ELSE 0 END
         ELSE NULL END AS Blacklisted,
    NULL::timestamp AS TarikhMulaKFAMKBAM
FROM airbyte_internal.dbo_raw__stream_vwlzs_asnaf
LIMIT 1000;
