SELECT
    (_airbyte_data->>'OwningUser')::text as SnapshotID,
    (_airbyte_data->>'vwlzs_asnafId')::text as AsnafID,
    (_airbyte_data->>'vwlzs_AsnafRegistrationIdName')::text as AsnafName,
    (_airbyte_data->>'vwlzs_CreatedBy')::text as Createdby,
    TO_CHAR((_airbyte_data->>'vwlzs_CreatedOn')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') as DateCreated,
    NULL::int as asnafStatus,
    (_airbyte_data->>'vwlzs_name')::text as Name,
    (_airbyte_data->>'vwlzs_IdentificationType')::int as IdentificationType,
    TO_CHAR((_airbyte_data->>'vwlzs_DateofBirth')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') as DateofBirth,
    (_airbyte_data->>'vwlzs_Age')::int as Age,
    (_airbyte_data->>'vwlzs_MaritalStatus')::int as MaritalStatus,
    NULL::text as Working,
    (_airbyte_data->>'vwlzs_Healthlevel')::int as Healthlevel,
    (_airbyte_data->>'vwlzs_Condition')::int as PhysicalCondition,
    (_airbyte_data->>'vwlzs_BankName')::text as Bank,
    (_airbyte_data->>'vwlzs_OtherName')::text as OtherName,
    (_airbyte_data->>'vwlzs_nric')::text as IdentificationNumIC,
    (_airbyte_data->>'vwlzs_PlaceofBirth')::text as BirthLocation,
    CASE WHEN (_airbyte_data->>'vwlzs_Gender') IN ('true', 'false')
         THEN CASE WHEN (_airbyte_data->>'vwlzs_Gender')::boolean IS TRUE THEN 1 ELSE 0 END
         ELSE NULL END as Gender,
    NULL::timestamp as IfMuallafDateInIslam,
    (_airbyte_data->>'vwlzs_Salary')::money as Salary,
    (_airbyte_data->>'vwlzs_Notes')::text as Remarks,
    (_airbyte_data->>'vwlzs_ModeofPayment')::int as ModeofPayment,
    (_airbyte_data->>'vwlzs_BankAccountNo')::text as BankAccountNum,
    (_airbyte_data->>'vwlzs_Residentialstatus')::int as ResidentialStatus,
    (_airbyte_data->>'vwlzs_PeriodStayInSelangorYear')::int as PeriodStayInSelangorYear,
    (_airbyte_data->>'vwlzs_Street1')::text as Street1,
    (_airbyte_data->>'vwlzs_Street2')::text as Street2,
    (_airbyte_data->>'vwlzs_Street3')::text as Street3,
    (_airbyte_data->>'vwlzs_City')::text as City,
    (_airbyte_data->>'vwlzs_Postcode')::text as Postcode,
    (_airbyte_data->>'vwlzs_BranchName')::text as Branch,
    NULL::text as BranchID,
    (_airbyte_data->>'vwlzs_State')::int as State,
    (_airbyte_data->>'vwlzs_Country')::int as Country,
    (_airbyte_data->>'vwlzs_TelephoneNoHome')::text as TelephoneNoHome,
    (_airbyte_data->>'vwlzs_TelephoneNoOffice')::text as TelephoneNoOffice,
    (_airbyte_data->>'vwlzs_MobileNo')::text as MobilePhoneNum,
    (_airbyte_data->>'vwlzs_Email')::text as Emel,
    (_airbyte_data->>'vwlzs_Schooling')::int as Schooling,
    (_airbyte_data->>'vwlzs_Education')::int as Education,
    (_airbyte_data->>'vwlzs_HighestEducation')::int as HighestEducation,
    NULL::timestamp as DateofApplication,
    NULL::int as RegistrationPortalId,
    NULL::int as RegistrationStatus,
    NULL::int as RegistrationType,
    NULL::text as ExitAsnafRemark,
    NULL::text as ExitAsnafReason,
    TO_CHAR((_airbyte_data->>'vwlzs_DeceasedDate')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') as DeceasedDate,
    NULL::text as recipientType,
    NULL::text as recipient,
    (_airbyte_data->>'vwlzs_District')::text as District,
    NULL::text as DistrictID,
    (_airbyte_data->>'vwlzs_Mosque')::text as Mosque,
    NULL::text as MosqueID,
    NULL::text as JenisPendaftaran,
    (_airbyte_data->>'vwlzs_Status')::text as Status,
    NULL::int as Statecode,
    NULL::text as StatusAsnaf,
    NULL::text as PostJson,
    NULL::text as ReturnJson,
    NULL::text as CRMAsnafID,
    (_airbyte_data->>'vwlzs_PakId')::text as PINo,
    (_airbyte_data->>'vwlzs_RegType')::text as RegType,
    NULL::text as CRMReviewID,
    NULL::text as CRMRegistrationID,
    NULL::text as Relationship,
    NULL::text as MasihTanggungan,
    NULL::text as recipientTypeAsnaf,
    NULL::text as recipientTypeOrganization,
    NULL::text as Ename,
    NULL::text as Eposition,
    NULL::text as Eoffice,
    NULL::text as Erelation,
    (_airbyte_data->>'vwlzs_RemarkJobStatus')::text as reviewRemarks,
    NULL::text as resetBy,
    NULL::text as healthCronic,
    NULL::text as OKU_Physical,
    NULL::text as OKU_Type,
    NULL::text as OKU_Cause,
    NULL::text as OKU_Cause_Level,
    NULL::text as Uzur_Condition,
    (_airbyte_data->>'vwlzs_CareCosts')::text as carecosts,
    NULL::money as monthlytotal,
    (_airbyte_data->>'vwlzs_Sector')::text as sector,
    (_airbyte_data->>'vwlzs_WorkRemark')::text as remarkwork,
    (_airbyte_data->>'vwlzs_vehicle')::text as vehicle,
    NULL::text as vehicleothers,
    NULL::text as namamajikan,
    NULL::text as fishermenpoultryagricultural,
    NULL::text as sewinghandicraftscookingnursery,
    (_airbyte_data->>'vwlzs_Service')::text as service,
    NULL::text as othersskill,
    (_airbyte_data->>'vwlzs_othersremarks')::text as othersskillremarks,
    NULL::text as carpentry,
    (_airbyte_data->>'vwlzs_Business')::text as business,
    NULL::text as portalID,
    NULL::text as regstatus,
    (_airbyte_data->>'vwlzs_kadarsewa')::money as kadarsewa,
    NULL::text as amilID,
    NULL::text as AsnafCategory,
    (_airbyte_data->>'vwlzs_ModifiedBy')::uuid as ModifiedBy,
    TO_CHAR((_airbyte_data->>'vwlzs_ModifiedOn')::timestamp, 'YYYY-MM-DD"T"HH24:MI:SS.MS') as ModifiedOn,  -- ISO 8601 format
    NULL::int as hadkifayahRate,
    NULL::text as hadkifayah,
    (_airbyte_data->>'vwlzs_SAPCode')::text as SAPCode,
    (_airbyte_data->>'vwlzs_sapremarks')::text as SAPRemarks,
    CASE WHEN (_airbyte_data->>'vwlzs_SAPIndicator') IN ('true', 'false')
         THEN CASE WHEN (_airbyte_data->>'vwlzs_SAPIndicator')::boolean IS TRUE THEN 1 ELSE 0 END
         ELSE NULL END as SAPIndicator,
    CASE WHEN (_airbyte_data->>'vwlzs_Blacklisted') IN ('true', 'false')
         THEN CASE WHEN (_airbyte_data->>'vwlzs_Blacklisted')::boolean IS TRUE THEN 1 ELSE 0 END
         ELSE NULL END as Blacklisted,
    NULL::timestamp as TarikhMulaKFAMKBAM
FROM airbyte_internal.dbo_raw__stream_vwlzs_asnaf
ORDER BY (_airbyte_data->>'vwlzs_CreatedOn')::timestamp DESC
LIMIT 30000;
